package org.camelcookbook.ws.payment_service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2015-02-10T06:27:40.993Z
 * Generated source version: 3.0.2
 * 
 */
@WebService(targetNamespace = "http://ws.camelcookbook.org/payment-service", name = "Payment")
@XmlSeeAlso({org.camelcookbook.ws.payment_service.types.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Payment {

    @WebMethod
    @WebResult(name = "transferResponse", targetNamespace = "http://ws.camelcookbook.org/payment-service/types", partName = "response")
    public org.camelcookbook.ws.payment_service.types.TransferResponse transferFunds(
        @WebParam(partName = "payload", name = "transferRequest", targetNamespace = "http://ws.camelcookbook.org/payment-service/types")
        org.camelcookbook.ws.payment_service.types.TransferRequest payload
    ) throws FaultMessage;
}
