package org.camelcookbook.ws.payment_service_v2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2015-01-30T12:42:24.070Z
 * Generated source version: 3.0.2
 * 
 */
@WebService(targetNamespace = "http://ws.camelcookbook.org/payment-service-v2", name = "Payment")
@XmlSeeAlso({org.camelcookbook.ws.payment_service_v2.types.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Payment {

    @WebMethod
    @WebResult(name = "transferResponse", targetNamespace = "http://ws.camelcookbook.org/payment-service-v2/types", partName = "response")
    public org.camelcookbook.ws.payment_service_v2.types.TransferResponse transferFunds(
        @WebParam(partName = "payload", name = "transferRequest", targetNamespace = "http://ws.camelcookbook.org/payment-service-v2/types")
        org.camelcookbook.ws.payment_service_v2.types.TransferRequest payload
    ) throws FaultMessage;

    @WebMethod
    @WebResult(name = "checkStatusResponse", targetNamespace = "http://ws.camelcookbook.org/payment-service-v2/types", partName = "response")
    public org.camelcookbook.ws.payment_service_v2.types.CheckStatusResponse checkStatus(
        @WebParam(partName = "payload", name = "checkStatusRequest", targetNamespace = "http://ws.camelcookbook.org/payment-service-v2/types")
        org.camelcookbook.ws.payment_service_v2.types.CheckStatusRequest payload
    ) throws FaultMessage;
}
